name: Test Workflow 2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'TEST_QA'
        type: choice
        options:
          - TEST_QA
          - TEST_PROD
  workflow_call:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'TEST_QA'
        type: string

env:
  environment: ${{inputs.environment}}

jobs:
  test-input-values:
    name: expose env variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
      - run: |
          echo "Running tests in ${{ env.environment }} environment"
  test-workflow1:
    needs: [test-input-values]
    uses: ./.github/workflows/test-workflow1.yml
    secrets: inherit
    with:
      environment: ${{ needs.test-input-values.outputs.environment }}
