name: Test Workflow 3
on:
  workflow_dispatch:
  schedule:
    - cron: '43 0 * * *'

env:
  environment: 'TEST_QA'

jobs:
  test-input-values:
    name: expose env variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
      - run: |
          echo "Running tests in ${{ env.environment }} environment"
  test-workflow2:
    needs: [test-input-values]
    uses: ./.github/workflows/test-workflow2.yml
    secrets: inherit
    with:
      environment: ${{ needs.test-input-values.outputs.environment }}
