name: Test Workflow 1

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      selected_function:
        description: 'Select the Python task to run'
        required: true
        default: 'run all tasks'
        type: choice
        options:
          - run all tasks
          - task1
          - task2
      environment:
        description: 'Select the environment'
        required: true
        default: 'TEST_QA'
        type: choice
        options:
          - TEST_QA
          - TEST_PROD
  workflow_call:
    inputs:
      selected_function:
        description: 'Select the Python task to run'
        default: 'run all tasks'
        type: string
      environment:
        description: 'Select the environment'
        default: 'TEST_QA'
        type: string  

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Set environment variables
      run: |
        echo "SELECTED_FUNCTION=${{ inputs.selected_function }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
    
    - name: Run Python Script
      run: |
        python3 task1.py "${{ env.SELECTED_FUNCTION }}" "${{ env.ENVIRONMENT }}"

 
